name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Update server via ssh
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
    
      - name: Allow to run gradlew
        run: chmod +x gradlew
      - name: Try to build
        run: docker build .
        
    
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER_LOGIN }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          script_stop: true
          timeout: 30m
          command_timeout: 60m
          script: cd /home/deployer;bash maiserver.sh
